name: Daily Heartbeat

on:
  schedule:
    # Runs every day at 09:10 UTC (11:10 in Amsterdam during DST)
    - cron: "10 9 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          ref: master
          persist-credentials: true

      - name: Configure Git
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Make 0–7 spaced commits
        env:
          FILEPATH: .keepalive/$(date -u +%Y).md
        run: |
          mkdir -p .keepalive
          commits=$(shuf -i 0-7 -n 1)
          echo "Will make $commits commit(s) today."
          for i in $(seq 1 $commits); do
            echo "$(date -u +"%Y-%m-%d %H:%M:%S") — heartbeat [$i/$commits]" >> "$FILEPATH"
            git add "$FILEPATH"
            git commit -m "chore: heartbeat $(date -u +"%F %T") [$i/$commits]"
            # Random pause between commits (60–900 seconds) to spread them out
            if [ "$i" -lt "$commits" ]; then
              sleep $(( 60 + RANDOM % 840 ))
            fi
          done
          git push origin HEAD:master
